#!/usr/bin/env python3
"""Turn a box-walk probe into a spin probe: same prefix, twelve-times-shorter legs.

The nine `movies/levelN.zmv` probes all end the same way -- hold Y and walk
Right/Down/Left/Up for 180 frames each -- and that tail was written to make the
level *run*, not to make the player *aim*. It did its job: it produced a census
of eleven unported handlers. What it cannot do is hit anything, and the coverage
table says so in whole families at a time. On level 21 `$81:9B6B` is on the
display list for 96 of 126 sampled frames, three copies at once, and every call
it makes takes the ignore path.

The reason is visible only when the player's positions and the creatures' are
read side by side: **these things walk at the player**, and a 180-frame leg means
the player spends almost all of its time facing away from the crowd it is towing.
A shot leaves in the direction you are facing, so a chaser is by construction
behind it.

So the tail here is the same twelve directions at 30 frames instead of 180. The
player stays roughly where it started -- four legs of 30 frames cancel out -- and
faces all four directions once a second, which is what puts a shot into something
that is walking into you. On level 21 that is the difference between 0 hits and
35 in the same 2,100 frames.

    python tools/make_spin_probe.py movies/level21.zmv movies/level21-spin.zmv
    python tools/make_spin_probe.py movies/level5.zmv movies/level5-spin.zmv --leg 20

`--leg` is the knob worth turning: too short and the player never moves far
enough to face a new direction cleanly, too long and it is a box walk again.
"""

import argparse
import re
import sys

DIRS = ["Right", "Down", "Left", "Up"]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("src")
    ap.add_argument("out")
    ap.add_argument("--leg", type=int, default=30, help="frames per leg (30)")
    ap.add_argument("--lookback", type=int, default=0,
                    help="frames of a reversed leg after each one (0 = off)")
    ap.add_argument("--start", type=int, default=2500,
                    help="frame the spin begins (2500)")
    ap.add_argument("--end", type=int, default=4600,
                    help="frame it stops pressing (4600)")
    ap.add_argument("--fire", default="Y", help="the fire button held (Y)")
    args = ap.parse_args()

    src = open(args.src, encoding="utf-8").read().splitlines()
    # Everything before the first gameplay leg is the password prefix and the
    # player-select Start, which is what this is reusing; a movie's own tail is
    # exactly what is being replaced.
    prefix = [l for l in src
              if re.match(r"^\d+\s", l) and int(l.split()[0]) < args.start]
    if not prefix:
        sys.exit("no timed lines before frame %d in %s" % (args.start, args.src))

    tail, frame, i = [], args.start, 0
    while frame < args.end:
        tail.append("%d   %s+%s" % (frame, DIRS[i % 4], args.fire))
        frame += args.leg
        i += 1
        if args.lookback and frame < args.end:
            # The same leg walked backwards, long enough to turn and shoot and
            # short enough not to undo the travel. A short leg alone keeps the
            # player where it started, which is right for a level whose
            # creatures come to you and wrong for one whose do not.
            tail.append("%d   %s+%s" % (frame, DIRS[(i + 1) % 4], args.fire))
            frame += args.lookback
    tail.append("%d   -" % frame)

    with open(args.out, "w", encoding="utf-8") as f:
        f.write("# Spin probe generated by tools/make_spin_probe.py from %s.\n"
                "# %d legs of %d frames from frame %d, fire held throughout.\n"
                "# Replace this header with what the movie turned out to be for.\n"
                % (args.src, i, args.leg, args.start))
        f.write("\n".join(prefix) + "\n" + "\n".join(tail) + "\n")
    print("%s: %d prefix lines, %d legs of %d frames"
          % (args.out, len(prefix), i, args.leg))


if __name__ == "__main__":
    main()
